---

- name: "Include konfig vars"
  include_vars: "konfig.yml"

- include_tasks: konsole.yml

- name: "Ensure syntax highlighting themes directory exist"
  file:
    dest: '{{ data_home }}/org.kde.syntax-highlighting/themes'
    state: directory

- name: "Install Spacemacs-like syntax highlighting theme"
  copy:
    src: Spacemacs-like.theme
    dest: '{{ data_home }}/org.kde.syntax-highlighting/themes/Spacemacs-like.theme'

- name: "Update ini konfig files"
  include_tasks: update_ini_konfig.yml
  loop: '{{ kde_config_files | dict2items }}'

- name: "Rebuild the system konfiguration cache"
  shell: "kbuildsycoca5"
