---

- name: "Install Konsole kolour scheme"
  copy:
    src: "konsole/Terminal.app Basic.colorscheme"
    dest: "{{ data_home }}/konsole/Terminal.app Basic.colorscheme"

- name: "Install Konsole profile"
  template:
    src: "konsole/Basic.profile.j2"
    dest: "{{ data_home }}/konsole/Basic.profile"
