---

- name: "Include OS-specific vars"
  include_vars: "{{ ansible_facts['system'] | lower }}.yml"

- name: "Include OS-specific tasks"
  include_tasks: "{{ ansible_facts['system'] | lower }}.yml"

- include_tasks: konfigure.yml
