---
# Nasty workaround because Ansible can't loop over blocks, which would be super
# handy when handling nested hashes
#
# Kalled from: update_ini_konfig.yml

- name: "Update konfig for {{ item.key }} : {{ konfig.key }}"
  ini_file:
    path: "~/.config/{{ item.key}}"
    section: '{{ konfig.key }}'
    option: '{{ konfig_entry.key }}'
    value: '{{ konfig_entry.value }}'
    no_extra_spaces: yes
  loop: '{{ konfig.value | dict2items }}'
  loop_control:
    loop_var: konfig_entry
