---
- name: "Install Emacs"
  package:
    name: emacs
    state: present
  become: true
  become_user: root
  when: ansible_facts['system'] == "Linux"

- name: "Install Emacs from cask"
  homebrew_cask:
    name: emacs
    state: present
  when: ansible_facts['system'] != "Linux"

- name: "Checkout Spacemacs repo"
  git:
    repo: "https://github.com/syl20bnr/spacemacs.git"
    dest: "~/.emacs.d"

- name: "Install Spacemacs config"
  copy:
    src: "dotspacemacs"
    dest: "~/.spacemacs"
    force: false

- name: "Create ~/.spacemacs.d"
  file:
    path: "~/.spacemacs.d"
    state: directory

- name: "Create ~/.spacemacs.d/layers"
  file:
    path: "~/.spacemacs.d/layers"
    state: directory

- name: "Touch ~/.spacemacs.d/user-config.el"
  file:
    path: "~/.spacemacs.d/user-config.el"
    state: touch

- name: "Remove ~/.emacs init file"
  file:
    path: "~/.emacs"
    state: absent
