---
- name: "Install applications from cask"
  homebrew_cask:
    name:
      - firefox
      - telegram
      - element
      - xquartz
    state: present

- name: "Configure NFS"
  ansible.builtin.template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: wheel
    mode: '0644'
  become: yes
  become_user: root
