---
- name: "Install applications from cask"
  homebrew_cask:
    name:
      - firefox
      - telegram
      - element
      - xquartz
    state: present

- name: "Configure NFS"
  ansible.builtin.template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: wheel
    mode: '0644'
  become: yes
  become_user: root

##################################
# install EurKEY keyboard layout #
##################################

- set_fact:
    eurkey_commit: "05cdbd33771d5f17f7225d63960712163df5744b"
    eurkey_repo: "jonasdiemer/EurKEY-Mac"

- name: "Install EurKEY keyboard layout"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/{{ eurkey_repo }}/{{ eurkey_commit }}/{{ item }}"
    dest: "/Library/Keyboard Layouts/{{ item }}"
    force: yes
  loop:
    - "EurKEY.keylayout"
    - "EurKEY.icns"
  become: yes
  become_user: root

############
# defaults #
############

- name: "Allow dragging the window anywhere by holding down ⌃⌘"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSWindowShouldDragOnGesture
    type: bool
    value: true

#####################################
# allow sudo unlocking via Touch ID #
#####################################

- name: "Configure sudo PAM policy to unlock with Touch ID"
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    line: 'auth       sufficient     pam_tid.so'
    insertafter: '^# '
    firstmatch: yes
  become: yes
  become_user: root
