---
- set_fact:
    fortunes_base_path: "/usr/local/share/games/fortunes"
  when: ansible_system == 'Darwin'
- set_fact:
    fortunes_base_path: "/usr/share/fortune"
  when: ansible_system != 'Darwin'

- name: "Install fun packages"
  package:
    name:
      - cowsay
      - figlet
      - fortune
    state: present
  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
  become_user: root

- name: "Create custom cows dir"
  file:
    path: "~/.local/share/cows"
    state: directory

- name: "Install custom cowsay cows to ~/.local/share/cows"
  copy:
    src: "{{ item }}"
    dest: "~/.local/share/{{ item }}"
    force: yes
  loop:
    - cows/fox.cow
    - cows/parrot.cow

- name: "Install rrerrNet fortunes"
  get_url:
    url: "https://raw.githubusercontent.com/rrerrNet/fortunes/master/{{ item }}"
    dest: "{{ fortunes_base_path }}/{{ item }}"
    force: yes
  loop:
    - rrerrnet
  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
  become_user: root

- name: "Compile rrerrNet fortunes strfile"
  shell: "strfile {{ item }}"
  args:
    chdir: "{{ fortunes_base_path }}"
  loop:
    - rrerrnet
  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
  become_user: root
