---
- name: "Include OS-specific tasks"
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: "Install base packages"
  package:
    name:
      - dialog
      - htop
      - ncdu
      - p7zip
      - pngcrush
      - the_silver_searcher
      - tmux
      - xmp
    state: present
  become: "{{ 'false' if ansible_facts['system'] == 'Darwin' else 'true' }}"
  become_user: root

- name: "Setup fun things"
  import_tasks: fun.yml
