---
- name: "Install base applications"
  package:
    name:
      - MozillaFirefox
      - seafile-client
      - telegram-desktop
      - keepassxc
    state: present

- name: "Install C/C++ devel pattern"
  zypper:
    name: "devel_C_C++"
    state: present
    type: pattern
