---
- set_fact:
    ruby_build_dependencies:
      - openssl
      - libyaml
  when: ansible_system == 'Darwin'
- set_fact:
    ruby_build_dependencies:
      - libopenssl-devel
      - libyaml-devel
      - readline-devel
  when: ansible_system != 'Darwin'

- name: "Install build dependencies"
  package:
    name: "{{ ruby_build_dependencies }}"
    state: present
  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
  become_user: root

- name: "Checkout rbenv repo"
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~/.rbenv"

- name: "Create plugins directory"
  file:
    state: directory
    path: "~/.rbenv/plugins"

- name: "Install plugins"
  git:
    repo: "{{ item.repo }}"
    dest: "~/.rbenv/plugins/{{ item.name }}"
  loop: "{{ rbenv.plugins }}"

- name: "Set default gems"
  copy:
    src: "default-gems"
    dest: "~/.rbenv/default-gems"

- name: "Install gemrc"
  copy:
    src: "gemrc"
    dest: "~/.gemrc"
    force: false

- name: "Remove irbrc"
  file:
    path: "~/.irbrc"
    state: absent

- name: "Install rubies"
  shell: |-
    $SHELL -lc "~/.rbenv/bin/rbenv install --skip-existing {{ item }}"
  loop: "{{ rbenv.rubies }}"

- name: "Set ruby {{ rbenv.default_ruby }} as default"
  shell: |-
    $SHELL -lc "~/.rbenv/bin/rbenv global {{ rbenv.default_ruby }} && ~/.rbenv/bin/rbenv rehash"
