---
# sigh

- name: "Install required fonts"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "bitstream-vera-fonts"
    - "twemoji-color-font"
  become: true
  become_user: root

- name: "Create user-specific fontconfig config dir"
  file:
    path: "~/.config/fontconfig/conf.d"
    state: directory

- name: "Install fontconfig overrides for emoji usage"
  copy:
    src: "10-emoji.conf"
    dest: "~/.config/fontconfig/conf.d/10-emoji.conf"
    force: yes
