---
- name: "Create temp dir"
  tempfile:
    state: directory
  register: tmpdir

- name: "Download Input font with monaco configuration"
  get_url:
    url: "https://input.djr.com/build/?fontSelection=whole&a=ss&g=ss&i=serifs&l=serifs&zero=slash&asterisk=0&braces=0&preset=monaco&line-height=1.2&accept=I+do&email="
    dest: "{{ tmpdir.path }}/input.zip"
  
- name: "Unpack Input font"
  unarchive:
    src: "{{ tmpdir.path }}/input.zip"
    dest: "{{ tmpdir.path }}"

- name: "Find TTF files in unpacked archive"
  find:
    pattern: "*.ttf"
    paths: "{{ tmpdir.path }}"
    recurse: true
  register: ttf_found

- name: "Create {{ fonts_base_path }} if it does not exist"
  file:
    path: "{{ fonts_base_path }}"
    state: directory
    mode: "0755"
  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
  become_user: root

- name: "Install TTF files to {{ fonts_base_path }}"
  copy:
    src: "{{ item.path }}"
    dest: "{{ fonts_base_path }}/{{ item.path | basename }}"
  loop: "{{ ttf_found.files }}"
  become: "{{ 'false' if ansible_system == 'Darwin' else 'true' }}"
  become_user: root

- name: "Update fontconfig caches"
  shell: "fc-cache -fv"
  when: ansible_system != 'Darwin'
