---
- name: "Create temp dir"
  tempfile:
    state: directory
  register: tmpdir

- name: "Download Input font with monaco configuration"
  get_url:
    url: "http://input.fontbureau.com/build/?fontSelection=whole&a=ss&g=ss&i=serifs&l=serifs&zero=slash&asterisk=0&braces=0&preset=monaco&line-height=1.2&accept=I+do&email="
    dest: "{{ tmpdir.path }}/input.zip"
  
- name: "Unpack Input font"
  unarchive:
    src: "{{ tmpdir.path }}/input.zip"
    dest: "{{ tmpdir.path }}"

- name: "Find TTF files in unpacked archive"
  find:
    pattern: "*.ttf"
    paths: "{{ tmpdir.path }}"
    recurse: true
  register: ttf_found

- name: "Install TTF files to ~/Library/Fonts"
  copy:
    src: "{{ item.path }}"
    dest: "~/Library/Fonts/{{ item.path | basename }}"
  loop: "{{ ttf_found.files }}"
